const DATA_ROWS: { feature: string; data: string; goesTo: string; storedWhere: string }[] = [
  {
    feature: "Weather",
    data: "Approximate geographic coordinates, obtained via your browser's Geolocation API",
    goesTo: "Transmitted directly to Open-Meteo (api.open-meteo.com) to retrieve current conditions",
    storedWhere: "Coordinates cached locally in chrome.storage.sync",
  },
  {
    feature: "Time on Sites (disabled by default)",
    data: "The hostname of the active tab only; full URLs, page content, and inactive tabs are never accessed",
    goesTo: "Not transmitted anywhere; processed and retained exclusively on your device",
    storedWhere: "chrome.storage.local; deleted automatically after three days and reset daily",
  },
  {
    feature: "GitHub, Chess.com, WakaTime, Steam, MonkeyType (all disabled by default)",
    data: "A username or API key that you provide directly",
    goesTo: "Transmitted directly to the corresponding third-party service's public API",
    storedWhere: "chrome.storage.sync",
  },
  {
    feature: "Crypto Prices (disabled by default)",
    data: "The coin list and currency you configure",
    goesTo: "Transmitted directly to CoinGecko's public price API",
    storedWhere: "chrome.storage.sync",
  },
  {
    feature: "Greeting Holiday Lookup",
    data: "Today's date and the country you select",
    goesTo: "Transmitted directly to the public Nager.Date holiday API",
    storedWhere: "chrome.storage.sync (country selection only)",
  },
  {
    feature: "Search Mode",
    data: "Text you type while Search Mode is active",
    goesTo: "Transmitted directly to Google Search, or used to navigate to a URL if the input resembles one",
    storedWhere: "Not retained by the Extension",
  },
  {
    feature: "Preferences",
    data: "Your configuration choices (theme, module order, sound settings, etc.)",
    goesTo: "Not transmitted anywhere",
    storedWhere: "chrome.storage.sync",
  },
];

export default function Privacy() {
  return (
    <div className="options-root privacy-root">
      <h1>Privacy Policy</h1>
      <p className="hint">
        Split Flap Display (the "Extension") — Effective date: July 2026
      </p>

      <section>
        <h2>1. Introduction</h2>
        <p>
          This Privacy Policy describes how the Split Flap Display browser
          extension (the "Extension," "we," or "us") handles information in
          connection with your use of the Extension. It is intended to give
          you a complete and accurate account of what data the Extension
          touches, where that data goes, and the choices available to you.
        </p>
        <p>
          By installing and using the Extension, you agree to the practices
          described in this Policy. If you do not agree with these
          practices, please do not install or use the Extension.
        </p>
      </section>

      <section>
        <h2>2. Summary</h2>
        <p>
          The Extension operates entirely on your local device. We do not
          operate any backend server, and we do not collect, receive,
          transmit to ourselves, or otherwise have access to any data
          generated by your use of the Extension. Where the Extension
          communicates over the network, it does so directly between your
          browser and the specific third-party service required for the
          feature in question, and only when you have enabled and, where
          applicable, configured that feature yourself.
        </p>
      </section>

      <section>
        <h2>3. Information Handled by Each Feature</h2>
        <p>
          The table below summarizes every category of data the Extension
          may handle, its destination, and where, if anywhere, it is
          retained.
        </p>
        <table className="privacy-table">
          <thead>
            <tr>
              <th>Feature</th>
              <th>Data Involved</th>
              <th>Destination</th>
              <th>Retention</th>
            </tr>
          </thead>
          <tbody>
            {DATA_ROWS.map((row) => (
              <tr key={row.feature}>
                <td>{row.feature}</td>
                <td>{row.data}</td>
                <td>{row.goesTo}</td>
                <td>{row.storedWhere}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section>
        <h2>4. Browser Permissions</h2>
        <p><strong>4.1 The "tabs" permission.</strong> The optional Time on
          Sites feature requires the ability to determine which website is
          displayed in the active tab in order to measure time spent per
          site. This is the sole purpose of the <code>tabs</code> permission
          requested by the Extension. It has no effect unless you
          affirmatively enable the feature in Settings, where it is disabled
          by default; disabling it at any time immediately halts further
          tracking. The Extension does not access page content, form data,
          or tabs other than the currently active one, regardless of
          whether this feature is enabled.
        </p>
        <p><strong>4.2 The "alarms" permission.</strong> Used solely to
          periodically persist and prune data associated with the Time on
          Sites feature. This permission has no effect if that feature is
          disabled.
        </p>
      </section>

      <section>
        <h2>5. Third-Party Services</h2>
        <p>
          The Extension communicates with the following services, solely
          when the corresponding feature has been enabled and, where
          applicable, configured by you:
        </p>
        <ul>
          <li><strong>Open-Meteo</strong> — receives approximate coordinates; no authentication required.</li>
          <li><strong>GitHub REST API</strong> — receives the username you provide; no authentication required.</li>
          <li><strong>Chess.com Public API</strong> — receives the username you provide; no authentication required.</li>
          <li><strong>MonkeyType Public API</strong> — receives the username you provide; no authentication required.</li>
          <li><strong>WakaTime API</strong> — receives an API key generated and controlled by you.</li>
          <li><strong>Steam Web API</strong> — receives an API key and Steam ID generated and controlled by you.</li>
          <li><strong>CoinGecko Public API</strong> — receives the coin list and currency you configure; no authentication required.</li>
          <li><strong>Nager.Date Public API</strong> — receives the current date and your selected country code; no authentication required.</li>
          <li><strong>Google Search</strong> — receives search queries you submit while using Search Mode.</li>
        </ul>
        <p>
          Each of these services is governed by its own privacy policy and
          terms of service. We do not control, and are not responsible for,
          the data practices of these third parties. Our relationship with
          each service is limited to the direct API request initiated by
          your browser as a result of your configuration.
        </p>
      </section>

      <section>
        <h2>6. Compliance with the Digital Personal Data Protection Act, 2023 (India)</h2>
        <p>
          As the Extension does not transmit personal data to any server
          under our control, the obligations applicable to a Data Fiduciary
          under India's Digital Personal Data Protection Act, 2023 ("DPDP
          Act") are, in most respects, not engaged, as no such collection or
          processing occurs on infrastructure we operate. Nonetheless, in
          relation to the limited categories of data the Extension does
          handle locally, the Extension has been designed in accordance
          with the DPDP Act's foundational principles:
        </p>
        <ul>
          <li><strong>Consent</strong> — the most sensitive optional feature, Time on Sites, is disabled by default and requires an explicit, separate opt-in.</li>
          <li><strong>Purpose Limitation</strong> — each category of data is used exclusively for the specific feature it supports.</li>
          <li><strong>Data Minimization</strong> — the Time on Sites feature retains hostnames only.</li>
          <li><strong>Storage Limitation</strong> — data associated with Time on Sites is automatically deleted after three days.</li>
          <li><strong>Grievance Redressal</strong> — concerns may be directed to the contact in Section 9.</li>
        </ul>
      </section>

      <section>
        <h2>7. Your Rights and Choices</h2>
        <p>Because no data is retained outside your own device:</p>
        <ul>
          <li>
            <strong>Access and Deletion</strong> — uninstalling the Extension
            immediately removes all data stored locally by it. Individual
            settings may also be cleared at any time from the Settings page,
            or extension storage may be cleared directly via{" "}
            <code>chrome://extensions</code>.
          </li>
          <li>
            <strong>Withdrawal of Consent</strong> — disabling the Time on
            Sites feature immediately halts further data collection; any
            previously retained data for that feature is deleted
            automatically within three days regardless.
          </li>
        </ul>
      </section>

      <section>
        <h2>8. Children's Privacy</h2>
        <p>
          The Extension is not directed toward, and is not knowingly used
          to collect information from, children.
        </p>
      </section>

      <section>
        <h2>9. Contact</h2>
        <p>
          Questions or concerns regarding this Policy or the Extension's
          data practices may be directed to: <strong>abhimantrsingh@gmail.com</strong>
        </p>
      </section>

      <section>
        <h2>10. Changes to This Policy</h2>
        <p>
          We may update this Policy from time to time. Any revision will be
          reflected by an updated effective date above. Material changes —
          such as the introduction of a feature that transmits data to a
          new third party — will also be reflected in the Extension's
          listing on the Chrome Web Store at the time such changes take
          effect.
        </p>
      </section>

      <p className="hint">
        <a href="../options/index.html">← Back to Settings</a>
      </p>
    </div>
  );
}